# Generated by Django 4.2.28 on 2026-05-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="插件名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("collector", "采集插件"),
                            ("notifier", "通知插件"),
                            ("analyzer", "分析插件"),
                            ("reporter", "报告插件"),
                        ],
                        max_length=20,
                        verbose_name="插件类型",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Python 模块路径，例如: plugins.example_collector",
                        max_length=200,
                        verbose_name="插件路径",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="是否启用"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="插件配置"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "插件",
                "verbose_name_plural": "插件",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="租户名称")),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "免费版"),
                            ("pro", "专业版"),
                            ("enterprise", "企业版"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="套餐",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="域名"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "租户",
                "verbose_name_plural": "租户",
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Webhook名称")),
                ("url", models.URLField(verbose_name="目标URL")),
                (
                    "method",
                    models.CharField(
                        choices=[("POST", "POST"), ("GET", "GET"), ("PUT", "PUT")],
                        default="POST",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="自定义请求头"
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="用于HMAC签名，为空则不签名",
                        max_length=255,
                        verbose_name="签名密钥",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="订阅的事件类型: ['alert_triggered', 'report_generated', 'anomaly_detected']",
                        verbose_name="订阅事件类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="最后状态"
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后发送时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook端点",
                "verbose_name_plural": "Webhook端点",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="事件类型"),
                ),
                ("payload", models.JSONField(verbose_name="发送的数据")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("retrying", "重试中"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应状态码"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="响应内容"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, verbose_name="最大重试次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="system.webhookendpoint",
                        verbose_name="关联端点",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook日志",
                "verbose_name_plural": "Webhook日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
