# Generated by Django 5.2.9 on 2025-12-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='脚本名称')),
                ('script_type', models.CharField(choices=[('sh', 'Shell Script'), ('py', 'Python'), ('yml', 'Ansible Playbook')], default='sh', max_length=10, verbose_name='类型')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='高危脚本')),
                ('created_by', models.CharField(default='system', max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '脚本库',
                'verbose_name_plural': '脚本库',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('content', models.TextField(verbose_name='历史内容')),
                ('created_by', models.CharField(max_length=50, verbose_name='修改人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='变更备注')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='script_manager.script')),
            ],
            options={
                'verbose_name': '脚本历史',
                'verbose_name_plural': '脚本历史',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='执行人')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='执行参数')),
                ('concurrency', models.IntegerField(default=5, verbose_name='并发数')),
                ('timeout', models.IntegerField(default=60, verbose_name='单机超时(秒)')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='script_manager.script')),
                ('target_servers', models.ManyToManyField(to='cmdb.server', verbose_name='目标主机')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20, verbose_name='状态')),
                ('stdout', models.TextField(blank=True, verbose_name='标准输出')),
                ('stderr', models.TextField(blank=True, verbose_name='错误输出')),
                ('exit_code', models.IntegerField(null=True, verbose_name='退出码')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='script_manager.taskexecution')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.server')),
            ],
        ),
    ]
