# Generated by Django 6.0.4 on 2026-04-13 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cmdb", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertCorrelationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_patterns",
                    models.JSONField(default=dict, verbose_name="触发条件组合"),
                ),
                (
                    "root_cause_hint",
                    models.CharField(max_length=500, verbose_name="根因提示"),
                ),
                (
                    "suggested_action",
                    models.TextField(blank=True, verbose_name="建议操作"),
                ),
                (
                    "confidence_weight",
                    models.FloatField(default=0.8, verbose_name="置信度权重"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "告警关联规则",
                "verbose_name_plural": "告警关联规则",
            },
        ),
        migrations.CreateModel(
            name="EscalationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "match_rules",
                    models.JSONField(default=dict, verbose_name="匹配规则"),
                ),
                (
                    "escalation_steps",
                    models.JSONField(default=list, verbose_name="升级步骤"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "升级策略",
                "verbose_name_plural": "升级策略",
            },
        ),
        migrations.CreateModel(
            name="RemediationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="动作名称")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("script", "执行脚本"),
                            ("service_restart", "重启服务"),
                            ("disk_cleanup", "磁盘清理"),
                            ("scale_out", "扩容"),
                            ("webhook", "调用Webhook"),
                            ("custom", "自定义"),
                        ],
                        default="script",
                        max_length=50,
                    ),
                ),
                ("target_command", models.TextField(verbose_name="目标命令/脚本")),
                (
                    "severity_filter",
                    models.CharField(
                        default="P1,P2",
                        help_text="适用此动作的告警级别(逗号分隔)",
                        max_length=20,
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=300, verbose_name="超时秒数"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=1, verbose_name="最大重试"),
                ),
                (
                    "is_dangerous",
                    models.BooleanField(default=False, verbose_name="危险操作(需确认)"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "修复动作",
                "verbose_name_plural": "修复动作",
            },
        ),
        migrations.CreateModel(
            name="AgentToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Agent 名称")),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="API Token",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_agent_token",
                        to="cmdb.server",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Token",
                "verbose_name_plural": "Agent Tokens",
            },
        ),
        migrations.CreateModel(
            name="AlertGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="聚合组名")),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="指纹"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("firing", "触发中"), ("resolved", "已解决")],
                        db_index=True,
                        default="firing",
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(default="P2", max_length=10)),
                (
                    "alert_count",
                    models.IntegerField(default=0, verbose_name="告警总数"),
                ),
                ("first_fired_at", models.DateTimeField(auto_now_add=True)),
                ("last_fired_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "告警聚合组",
                "verbose_name_plural": "告警聚合组",
                "ordering": ["-last_fired_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="规则名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("threshold", "静态阈值"),
                            ("baseline", "动态基线"),
                            ("trend", "趋势检测"),
                            ("composite", "复合条件"),
                            ("absence", "消失检测"),
                            ("anomaly", "异常检测"),
                        ],
                        default="threshold",
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("P0", "致命 (Critical)"),
                            ("P1", "严重 (Major)"),
                            ("P2", "警告 (Warning)"),
                            ("P3", "提示 (Info)"),
                        ],
                        default="P1",
                        max_length=10,
                        verbose_name="严重级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "启用"),
                            ("disabled", "禁用"),
                            ("draft", "草稿"),
                        ],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "target_all",
                    models.BooleanField(default=True, verbose_name="应用于所有服务器"),
                ),
                (
                    "metric_name",
                    models.CharField(
                        default="cpu_usage",
                        help_text="cpu_usage / mem_usage / disk_usage / load_1min / net_in / net_out",
                        max_length=50,
                        verbose_name="监控指标",
                    ),
                ),
                (
                    "condition_config",
                    models.JSONField(
                        default=dict,
                        help_text="静态阈值:{'operator':'gt','value':90} / 动态基线:{'multiplier':1.5}",
                        verbose_name="条件配置",
                    ),
                ),
                (
                    "evaluate_interval",
                    models.PositiveIntegerField(
                        default=60, verbose_name="评估间隔(秒)"
                    ),
                ),
                (
                    "lookback_window",
                    models.PositiveIntegerField(default=5, verbose_name="回溯窗口(个)"),
                ),
                (
                    "cooldown_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="同一目标触发后N秒内不再重复触发",
                        verbose_name="冷却时间(秒)",
                    ),
                ),
                (
                    "max_alerts_per_hour",
                    models.PositiveIntegerField(
                        default=10, verbose_name="每小时最大告警数"
                    ),
                ),
                (
                    "notify_channels",
                    models.JSONField(
                        default=list,
                        help_text="['dingtalk','wechat','email']",
                        verbose_name="通知渠道",
                    ),
                ),
                (
                    "notify_template",
                    models.TextField(blank=True, default="", verbose_name="通知模板"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后触发时间"
                    ),
                ),
                (
                    "trigger_count",
                    models.PositiveIntegerField(default=0, verbose_name="累计触发次数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "预警规则",
                "verbose_name_plural": "预警规则",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("firing", "触发中"),
                            ("resolved", "已恢复"),
                            ("acknowledged", "已确认"),
                            ("silenced", "已静默"),
                        ],
                        default="firing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("severity", models.CharField(max_length=10, verbose_name="级别")),
                ("metric_name", models.CharField(max_length=50, verbose_name="指标名")),
                ("current_value", models.FloatField(verbose_name="当前值")),
                (
                    "threshold_value",
                    models.FloatField(blank=True, null=True, verbose_name="阈值/基线"),
                ),
                ("message", models.TextField(default="", verbose_name="告警消息")),
                ("detail", models.JSONField(default=dict, verbose_name="详细信息")),
                (
                    "fired_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="触发时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="恢复时间"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "notification_log",
                    models.JSONField(default=list, verbose_name="通知记录"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="cmdb.server",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="monitoring.alertrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警事件",
                "ordering": ["-fired_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertSilenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="静默名称")),
                (
                    "match_severity",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="匹配级别"
                    ),
                ),
                (
                    "match_rule_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="匹配规则"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("comment", models.TextField(blank=True, verbose_name="备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="生效中")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match_server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cmdb.server",
                    ),
                ),
            ],
            options={
                "verbose_name": "静默规则",
            },
        ),
        migrations.CreateModel(
            name="AnomalyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=50, verbose_name="指标名")),
                (
                    "detected_at",
                    models.DateTimeField(db_index=True, verbose_name="检测时间"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "高度异常"),
                            ("medium", "中度异常"),
                            ("low", "轻度异常"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="异常程度",
                    ),
                ),
                (
                    "anomaly_score",
                    models.FloatField(default=0.0, verbose_name="异常分数"),
                ),
                (
                    "method_used",
                    models.CharField(max_length=30, verbose_name="使用的检测方法"),
                ),
                (
                    "raw_values",
                    models.JSONField(default=list, verbose_name="原始数据序列"),
                ),
                ("current_value", models.FloatField(verbose_name="当前值")),
                (
                    "baseline_value",
                    models.FloatField(blank=True, null=True, verbose_name="基线值"),
                ),
                (
                    "deviation_percent",
                    models.FloatField(blank=True, null=True, verbose_name="偏差百分比"),
                ),
                (
                    "ai_diagnosis",
                    models.TextField(blank=True, default="", verbose_name="AI诊断结论"),
                ),
                (
                    "ai_confidence",
                    models.FloatField(blank=True, null=True, verbose_name="AI置信度"),
                ),
                (
                    "ai_analyzed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AI分析时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomaly_history",
                        to="monitoring.alertevent",
                        verbose_name="关联告警",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_histories",
                        to="cmdb.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "异常历史",
                "verbose_name_plural": "异常历史",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detector_name",
                    models.CharField(
                        choices=[
                            ("zscore", "Z-Score 检测器"),
                            ("iqr", "IQR 四分位距检测器"),
                            ("moving_avg", "移动平均检测器"),
                            ("rate_of_change", "变化率检测器"),
                            ("composite", "复合投票检测器"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="检测器名称",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "params",
                    models.JSONField(
                        default=dict,
                        help_text="zscore:{threshold:2.5} / iqr:{k:1.5} / moving_avg:{window:10,factor:2.0} / rate_of_change:{threshold:0.5,window:5} / composite:{vote_thr:0.6}",
                        verbose_name="参数配置",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "检测器配置",
                "verbose_name_plural": "检测器配置",
            },
        ),
        migrations.CreateModel(
            name="HealthScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scored_at", models.DateTimeField(db_index=True)),
                (
                    "overall_score",
                    models.FloatField(default=0.0, verbose_name="综合评分(0-100)"),
                ),
                ("cpu_score", models.FloatField(default=100)),
                ("mem_score", models.FloatField(default=100)),
                ("disk_score", models.FloatField(default=100)),
                ("network_score", models.FloatField(default=100)),
                ("availability_score", models.FloatField(default=100)),
                (
                    "alert_penalty",
                    models.FloatField(default=0, verbose_name="告警扣分"),
                ),
                (
                    "anomaly_penalty",
                    models.FloatField(default=0, verbose_name="异常扣分"),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "优秀(A)"),
                            ("B", "良好(B)"),
                            ("C", "一般(C)"),
                            ("D", "警告(D)"),
                            ("F", "严重(F)"),
                        ],
                        default="A",
                        max_length=10,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scores",
                        to="cmdb.server",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康评分",
                "verbose_name_plural": "健康评分",
                "ordering": ["-scored_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("dingtalk", "钉钉"),
                            ("wechat", "企业微信"),
                            ("email", "邮件"),
                            ("slack", "Slack"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                        verbose_name="渠道",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("retrying", "重试中"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "recipient",
                    models.JSONField(default=dict, verbose_name="接收者信息"),
                ),
                (
                    "content_summary",
                    models.TextField(blank=True, verbose_name="内容摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "alert_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_logs",
                        to="monitoring.alertevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知记录",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="RemediationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.TextField(blank=True, verbose_name="执行输出")),
                ("error_message", models.TextField(blank=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.remediationaction",
                    ),
                ),
                (
                    "alert_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.alertevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "修复记录",
                "verbose_name_plural": "修复记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RunbookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                (
                    "problem_pattern",
                    models.JSONField(default=dict, verbose_name="问题特征模式"),
                ),
                ("solution", models.TextField(verbose_name="解决方案")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("network", "网络"),
                            ("storage", "存储"),
                            ("memory", "内存"),
                            ("cpu", "计算"),
                            ("database", "数据库"),
                            ("application", "应用"),
                            ("security", "安全"),
                            ("general", "通用"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="标签(逗号分隔)"
                    ),
                ),
                (
                    "effectiveness_score",
                    models.FloatField(default=0.0, verbose_name="有效评分"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "运维知识条目",
                "verbose_name_plural": "运维知识条目",
                "ordering": ["-effectiveness_score"],
            },
        ),
        migrations.CreateModel(
            name="SavedDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "config",
                    models.JSONField(verbose_name="面板配置(图表类型/指标/布局)"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "已保存的仪表盘",
                "verbose_name_plural": "已保存的仪表盘",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceTopology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="服务名")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("application", "应用服务"),
                            ("database", "数据库"),
                            ("cache", "缓存"),
                            ("queue", "消息队列"),
                            ("lb", "负载均衡"),
                            ("storage", "存储"),
                            ("external", "外部服务"),
                        ],
                        default="application",
                        max_length=50,
                    ),
                ),
                (
                    "health_endpoint",
                    models.URLField(blank=True, verbose_name="健康检查URL"),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependents",
                        to="monitoring.servicetopology",
                        verbose_name="依赖的服务",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology_nodes",
                        to="cmdb.server",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务拓扑节点",
                "verbose_name_plural": "服务拓扑节点",
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["status", "rule_type"], name="monitoring__status_f46d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["severity"], name="monitoring__severit_75c81d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["status", "-fired_at"], name="monitoring__status_dd66e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["server", "status"], name="monitoring__server__f88733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyhistory",
            index=models.Index(
                fields=["server", "detected_at"], name="idx_anomaly_server_time"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyhistory",
            index=models.Index(
                fields=["metric_name", "detected_at"], name="idx_anomaly_metric_time"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyhistory",
            index=models.Index(fields=["severity"], name="idx_anomaly_severity"),
        ),
        migrations.AddIndex(
            model_name="healthscore",
            index=models.Index(
                fields=["server", "-scored_at"], name="monitoring__server__320f82_idx"
            ),
        ),
    ]
