# Generated by Django 5.2.9 on 2025-12-16 11:26

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(verbose_name='集群ID')),
                ('namespace', models.CharField(max_length=100, verbose_name='命名空间')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('data', models.TextField(verbose_name='配置内容')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('user', models.CharField(default='system', max_length=100, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='变更备注')),
            ],
            options={
                'verbose_name': '配置历史',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='集群名称')),
                ('kubeconfig', fernet_fields.fields.EncryptedTextField(verbose_name='KubeConfig')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='版本')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Agent Token')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.servergroup', verbose_name='所属分组')),
            ],
        ),
        migrations.CreateModel(
            name='NodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_token', models.CharField(db_index=True, max_length=64)),
                ('node_name', models.CharField(max_length=100)),
                ('node_ip', models.CharField(max_length=50)),
                ('kubelet_log', models.TextField(blank=True, verbose_name='Kubelet日志')),
                ('proxy_log', models.TextField(blank=True, verbose_name='Proxy日志')),
                ('runtime_status', models.TextField(blank=True, verbose_name='运行时状态')),
                ('cpu_usage', models.FloatField(default=0)),
                ('mem_usage', models.FloatField(default=0)),
                ('disk_usage', models.FloatField(default=0)),
                ('net_in', models.FloatField(default=0.0, verbose_name='入站流量(KB/s)')),
                ('net_out', models.FloatField(default=0.0, verbose_name='出站流量(KB/s)')),
                ('disk_read_rate', models.FloatField(default=0.0, verbose_name='磁盘读取(KB/s)')),
                ('disk_write_rate', models.FloatField(default=0.0, verbose_name='磁盘写入(KB/s)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('cluster_token', 'node_name')},
            },
        ),
    ]
